Repository AEYung/Together-server, pull requests merged in 2022-12, with the labels that each got.

#2 기본적인 시큐리티 설정 추가
  src/main/kotlin/com/aeyoung/together/TogetherApplication.kt
  src/main/kotlin/com/aeyoung/together/domain/member/Member.kt
  src/main/kotlin/com/aeyoung/together/domain/member/Role.kt
  src/main/kotlin/com/aeyoung/together/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/aeyoung/together/global/config/security/SecurityConfig.kt
  src/main/kotlin/com/aeyoung/together/global/config/security/jwt/JwtProperties.kt
  src/main/kotlin/com/aeyoung/together/global/entity/BaseIdEntity.kt
  src/main/kotlin/com/aeyoung/together/global/exception/BasicException.kt
  src/main/kotlin/com/aeyoung/together/global/exception/ErrorCode.kt
  src/main/kotlin/com/aeyoung/together/global/exception/ErrorResponse.kt
  src/main/kotlin/com/aeyoung/together/global/security/auth/AuthDetails.kt
  src/main/kotlin/com/aeyoung/together/global/security/auth/AuthDetailsService.kt
  src/main/kotlin/com/aeyoung/together/global/security/handler/CustomAccessDeniedHandler.kt
  src/main/kotlin/com/aeyoung/together/global/security/handler/CustomAuthenticationEntryPointHandler.kt
  src/main/kotlin/com/aeyoung/together/global/security/jwt/JwtExceptionFilter.kt
  src/main/kotlin/com/aeyoung/together/global/security/jwt/JwtReqFilter.kt
  src/main/kotlin/com/aeyoung/together/global/security/jwt/TokenProvider.kt
Labels: :twisted_rightwards_arrows: feature, :zero: priority: serious

#4 Devleoped SignUp
  src/main/kotlin/com/aeyoung/together/domain/member/Member.kt
  src/main/kotlin/com/aeyoung/together/domain/member/controller/AuthController.kt
  src/main/kotlin/com/aeyoung/together/domain/member/dto/req/MemberSignUpReqDto.kt
  src/main/kotlin/com/aeyoung/together/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/aeyoung/together/domain/member/service/impl/req/MemberSignUpServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/member/service/req/MemberSignUpService.kt
  src/main/kotlin/com/aeyoung/together/global/exception/BasicException.kt
  src/main/kotlin/com/aeyoung/together/global/exception/DuplicatedEmailException.kt
Labels: :twisted_rightwards_arrows: feature

#7 예외처리 개발
  build.gradle.kts
  src/main/kotlin/com/aeyoung/together/domain/member/exception/DuplicatedEmailException.kt
  src/main/kotlin/com/aeyoung/together/domain/member/presentation/controller/AuthController.kt
  src/main/kotlin/com/aeyoung/together/domain/member/presentation/dto/req/MemberSignUpReqDto.kt
  src/main/kotlin/com/aeyoung/together/domain/member/service/MemberSignUpService.kt
  src/main/kotlin/com/aeyoung/together/domain/member/service/impl/MemberSignUpServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/global/config/security/SecurityConfig.kt
  src/main/kotlin/com/aeyoung/together/global/exception/DuplicatedEmailException.kt
  src/main/kotlin/com/aeyoung/together/global/exception/handler/GlobalExceptionHandler.kt
Labels: :twisted_rightwards_arrows: feature, :one: priority: high, :wrench: refactoring

#9 made EmailAuth
  build.gradle.kts
  src/main/kotlin/com/aeyoung/together/domain/mail/EmailAuth.kt
  src/main/kotlin/com/aeyoung/together/domain/mail/MailSenderConfig.kt
  src/main/kotlin/com/aeyoung/together/domain/mail/controller/EmailAuthController.kt
  src/main/kotlin/com/aeyoung/together/domain/mail/dto/EmailAuthMailReqDto.kt
  src/main/kotlin/com/aeyoung/together/domain/mail/dto/EmailAuthReqDto.kt
  src/main/kotlin/com/aeyoung/together/domain/mail/exception/NotCheckedEmailException.kt
  src/main/kotlin/com/aeyoung/together/domain/mail/exception/WrongAuthCodeException.kt
  src/main/kotlin/com/aeyoung/together/domain/mail/exception/WrongEmailException.kt
  src/main/kotlin/com/aeyoung/together/domain/mail/repository/EmailAuthRepository.kt
  src/main/kotlin/com/aeyoung/together/domain/mail/service/EmailAuthSendingService.kt
  src/main/kotlin/com/aeyoung/together/domain/mail/service/EmailAuthVerifyingService.kt
  src/main/kotlin/com/aeyoung/together/domain/mail/service/Impl/EmailAuthSendingServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/mail/service/Impl/EmailAuthVerifyingServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/member/exception/DuplicatedEmailException.kt
  src/main/kotlin/com/aeyoung/together/domain/member/presentation/dto/req/MemberSignUpReqDto.kt
  src/main/kotlin/com/aeyoung/together/domain/member/service/impl/MemberSignUpServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/global/config/redis/RedisConfig.kt
  src/main/kotlin/com/aeyoung/together/global/config/security/SecurityConfig.kt
  src/main/kotlin/com/aeyoung/together/global/exception/ErrorCode.kt
Labels: :twisted_rightwards_arrows: feature, :one: priority: high

#10 add StudyRoom entity
  build.gradle.kts
  src/main/kotlin/com/aeyoung/together/domain/mail/controller/EmailAuthController.kt
  src/main/kotlin/com/aeyoung/together/domain/member/Member.kt
  src/main/kotlin/com/aeyoung/together/domain/study/StudyRoom.kt
  src/main/kotlin/com/aeyoung/together/domain/study/StudyTag.kt
  src/main/kotlin/com/aeyoung/together/domain/study/enums/StudyRoomScope.kt
  src/main/kotlin/com/aeyoung/together/domain/study/repository/StudyRoomRepository.kt
Labels: :twisted_rightwards_arrows: feature, :zero: priority: serious

#12 로그인 기능
  src/main/kotlin/com/aeyoung/together/domain/member/entity/RefreshToken.kt
  src/main/kotlin/com/aeyoung/together/domain/member/exception/MemberNotFoundException.kt
  src/main/kotlin/com/aeyoung/together/domain/member/exception/NotExistLoginMemberException.kt
  src/main/kotlin/com/aeyoung/together/domain/member/exception/WrongPasswordException.kt
  src/main/kotlin/com/aeyoung/together/domain/member/presentation/controller/AuthController.kt
  src/main/kotlin/com/aeyoung/together/domain/member/presentation/dto/req/MemberSignInReqDto.kt
  src/main/kotlin/com/aeyoung/together/domain/member/presentation/dto/req/MemberSignUpReqDto.kt
  src/main/kotlin/com/aeyoung/together/domain/member/presentation/dto/res/MemberSignInResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/aeyoung/together/domain/member/repository/RefreshTokenRepository.kt
  src/main/kotlin/com/aeyoung/together/domain/member/service/MemberSignInService.kt
  src/main/kotlin/com/aeyoung/together/domain/member/service/impl/MemberSignInServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/global/exception/ErrorCode.kt
  src/main/kotlin/com/aeyoung/together/global/security/auth/AuthDetailsService.kt
  src/main/kotlin/com/aeyoung/together/global/util/MemberUtil.kt
Labels: :twisted_rightwards_arrows: feature, :one: priority: high

#15 add 룸 필터링, 전체조회, 단독 조회
  src/main/kotlin/com/aeyoung/together/domain/study/exception/StudyNotFoundException.kt
  src/main/kotlin/com/aeyoung/together/domain/study/presentation/StudyRoomController.kt
  src/main/kotlin/com/aeyoung/together/domain/study/presentation/dto/res/StudyListResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/study/presentation/dto/res/StudyResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/study/repository/StudyRoomRepository.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/GetAllStudyService.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/GetOneStudyService.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/SearchStudyService.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/impl/GetAllStudyServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/impl/GetOneStudyServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/impl/SearchStudyServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/study/util/StudyTagUtil.kt
  src/main/kotlin/com/aeyoung/together/global/config/security/SecurityConfig.kt
  src/main/kotlin/com/aeyoung/together/global/exception/ErrorCode.kt
Labels: :twisted_rightwards_arrows: feature, :one: priority: high

#18 hotfix optional error, contorller dirction issue
  src/main/kotlin/com/aeyoung/together/domain/study/presentation/StudyRoomController.kt
  src/main/kotlin/com/aeyoung/together/domain/study/presentation/controller/StudyRoomController.kt
  src/main/kotlin/com/aeyoung/together/domain/study/presentation/dto/req/CreateStudyRoomReqDto.kt
Labels: :lady_beetle: bug, :zero: priority: serious

#21 Feature/refresh
  src/main/kotlin/com/aeyoung/together/domain/member/entity/RefreshToken.kt
  src/main/kotlin/com/aeyoung/together/domain/member/exception/RefreshTokenExpiredException.kt
  src/main/kotlin/com/aeyoung/together/domain/member/exception/RefreshTokenNotValidException.kt
  src/main/kotlin/com/aeyoung/together/domain/member/presentation/controller/AuthController.kt
  src/main/kotlin/com/aeyoung/together/domain/member/presentation/dto/res/RefreshResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/member/service/RefreshService.kt
  src/main/kotlin/com/aeyoung/together/domain/member/service/impl/MemberSignInServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/member/service/impl/RefreshServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/global/exception/ErrorCode.kt
  src/main/kotlin/com/aeyoung/together/global/security/jwt/TokenProvider.kt
  src/main/kotlin/com/aeyoung/together/global/security/jwt/exception/TokenExpiredException.kt
  src/main/kotlin/com/aeyoung/together/global/security/jwt/exception/TokenInValidException.kt
Labels: :twisted_rightwards_arrows: feature, :zero: priority: serious

#23 스터디 신청로직 개발
  src/main/kotlin/com/aeyoung/together/domain/member/Member.kt
  src/main/kotlin/com/aeyoung/together/domain/study/PendingUser.kt
  src/main/kotlin/com/aeyoung/together/domain/study/StudyRoom.kt
  src/main/kotlin/com/aeyoung/together/domain/study/exception/MemberNotHostException.kt
  src/main/kotlin/com/aeyoung/together/domain/study/exception/PendingUserNotFindException.kt
  src/main/kotlin/com/aeyoung/together/domain/study/exception/RoomCodeNotMatchException.kt
  src/main/kotlin/com/aeyoung/together/domain/study/exception/RoomScopeNotValidException.kt
  src/main/kotlin/com/aeyoung/together/domain/study/presentation/controller/StudyRoomController.kt
  src/main/kotlin/com/aeyoung/together/domain/study/presentation/dto/req/ApplyPermissionStudyReqDto.kt
  src/main/kotlin/com/aeyoung/together/domain/study/presentation/dto/req/CreateStudyRoomReqDto.kt
  src/main/kotlin/com/aeyoung/together/domain/study/presentation/dto/res/PendingListResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/study/presentation/dto/res/PendingResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/study/repository/PendingUserRepository.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/ApplyStudyService.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/ApproveStudyMemberService.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/GetPendingListService.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/impl/ApplyStudyServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/impl/ApproveStudyMemberServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/impl/CreateStudyRoomServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/impl/GetAllStudyServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/impl/GetPendingListServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/global/exception/ErrorCode.kt
Labels: :twisted_rightwards_arrows: feature, :zero: priority: serious

#24 Feature notice
  src/main/kotlin/com/aeyoung/together/domain/mail/presentation/dto/EmailAuthMailReqDto.kt
  src/main/kotlin/com/aeyoung/together/domain/member/Member.kt
  src/main/kotlin/com/aeyoung/together/domain/study/StudyNotice.kt
  src/main/kotlin/com/aeyoung/together/domain/study/StudyNoticeComment.kt
  src/main/kotlin/com/aeyoung/together/domain/study/StudyRoom.kt
  src/main/kotlin/com/aeyoung/together/domain/study/exception/StudyNoticeNotFoundException.kt
  src/main/kotlin/com/aeyoung/together/domain/study/presentation/controller/StudyRoomController.kt
  src/main/kotlin/com/aeyoung/together/domain/study/presentation/dto/req/WriteNoticeCommentReqDto.kt
  src/main/kotlin/com/aeyoung/together/domain/study/presentation/dto/req/WriteNoticeReqDto.kt
  src/main/kotlin/com/aeyoung/together/domain/study/repository/StudyNoticeCommentRepository.kt
  src/main/kotlin/com/aeyoung/together/domain/study/repository/StudyNoticeRepository.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/WriteNoticeCommentService.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/WriteNoticeService.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/impl/WriteNoticeCommentServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/impl/WriteNoticeServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/global/exception/ErrorCode.kt
Labels: :twisted_rightwards_arrows: feature, :one: priority: high

#26 Feature edit inform
  src/main/kotlin/com/aeyoung/together/domain/member/Member.kt
  src/main/kotlin/com/aeyoung/together/domain/study/StudyRoom.kt
  src/main/kotlin/com/aeyoung/together/domain/study/presentation/controller/StudyController.kt
  src/main/kotlin/com/aeyoung/together/domain/study/repository/StudyNoticeRepository.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/WriteNoticeCommentService.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/WriteNoticeService.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/StudyNotice.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/StudyNoticeComment.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/exception/StudyNoticeNotFoundException.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/controller/StudyRoomController.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/dto/req/UpdateStudyRoomReqDto.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/dto/req/WriteNoticeCommentReqDto.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/dto/req/WriteNoticeReqDto.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/repository/StudyNoticeCommentRepository.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/repository/StudyNoticeRepository.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/service/UpdateStudyRoomService.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/service/WriteNoticeCommentService.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/service/WriteNoticeService.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/service/impl/UpdateStudyRoomServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/service/impl/WriteNoticeCommentServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/service/impl/WriteNoticeServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/global/config/security/SecurityConfig.kt
Labels: :twisted_rightwards_arrows: feature, :one: priority: high

#29 마이페이지를 구성할때 호출할 api 개발
  src/main/kotlin/com/aeyoung/together/domain/member/presentation/controller/MemberController.kt
  src/main/kotlin/com/aeyoung/together/domain/member/presentation/dto/res/InfoStudyResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/member/presentation/dto/res/MemberInfoResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/member/service/GetMyInfoService.kt
  src/main/kotlin/com/aeyoung/together/domain/member/service/impl/GetMyInfoServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/study/presentation/dto/res/StudyResDto.kt
  src/main/kotlin/com/aeyoung/together/global/config/security/SecurityConfig.kt
Labels: :twisted_rightwards_arrows: feature, :one: priority: high

#30 Feature room info
  src/main/kotlin/com/aeyoung/together/domain/member/presentation/controller/AuthController.kt
  src/main/kotlin/com/aeyoung/together/domain/study/service/impl/CreateStudyRoomServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/StudyNoticeComment.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/controller/StudyRoomController.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/dto/req/UpdateStudyRoomReqDto.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/dto/res/CheckHostMemberResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/dto/res/HostRoomInfoResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/dto/res/MemberRoomInfoResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/dto/res/RoomMemberResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/dto/res/RoomMembersResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/dto/res/RoomNoticeCommentResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/dto/res/RoomNoticeCommentWriterResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/dto/res/RoomNoticeCommentsResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/dto/res/RoomNoticeResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/dto/res/RoomNoticeWriterResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/presentation/dto/res/RoomNoticesResDto.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/service/CheckHostMemberService.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/service/GetHostStudyInfoService.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/service/GetMemberStudyInfoService.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/service/impl/CheckHostMemberServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/service/impl/GetHostStudyInfoServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/service/impl/GetMemberStudyInfoServiceImpl.kt
  src/main/kotlin/com/aeyoung/together/domain/studyRoom/service/impl/UpdateStudyRoomServiceImpl.kt
Labels: :twisted_rightwards_arrows: feature, :one: priority: high

#33 webRtc를 위한 signaling 서버 세팅
  build.gradle.kts
  src/main/kotlin/com/aeyoung/together/domain/videoCall/presentation/VideoRoomController.kt
  src/main/kotlin/com/aeyoung/together/domain/videoCall/presentation/dto/SocketSession.kt
  src/main/kotlin/com/aeyoung/together/global/config/security/SecurityConfig.kt
  src/main/kotlin/com/aeyoung/together/global/config/socket/WebSocketConfig.kt
Labels: :twisted_rightwards_arrows: feature, :one: priority: high
